<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class places extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $places = [
            [
                'kategori_id' => 1,
                'mood_id' => 1,
                'nama_tempat' => 'Relasi Kopi Cibiru',
                'deskripsi' => 'Relasi Kopi Cibiru adalah coffeeshop dan resto yang buka 24 jam di Cibiru, Bandung. Populer di kalangan mahasiswa dan warga lokal karena suasananya yang nyaman, menu yang terjangkau, dan atmosfer sosialnya.',
                'alamat_lengkap' => 'Jl. Pandanwangi Jl. Cibiru Indah VIII No.03, Cinunuk, Kec. Cileunyi, Kabupaten Bandung, Jawa Barat 40625',
                'latitude' => -6.935866745202871,
                'longitude' => 107.72731538715281,
                'harga_min' => 25000,
                'harga_max' => 50000,
                'status_aktif' => true,
                'tempat_unggulan' => true,
                'created_by' => 1,
            ],
            [
                'kategori_id' => 1,
                'mood_id' => 1,
                'nama_tempat' => 'Kongsi',
                'deskripsi' => 'Restoran ini menjual berbagai macam jenis makanan/minuman seperti : Snacks Jajanan, Bakmie, Coffee Shop dengan harga yang terjangkau. Menu yang disediakan pun bermacam-macam dan anda bisa mencoba nya untuk dinikmati dengan keluarga atau saudara anda.',
                'alamat_lengkap' => 'Jl. Pandanwangi No.33, Cibiru Wetan, Kec. Cileunyi, Kabupaten Bandung, Jawa Barat 40625',
                'latitude' => -6.9326915164186556,
                'longitude' => 107.74103709874022,
                'harga_min' => 25000,
                'harga_max' => 50000,
                'status_aktif' => true,
                'tempat_unggulan' => false,
                'created_by' => 1,
            ],
            [
                'kategori_id' => 1,
                'mood_id' => 1,
                'nama_tempat' => 'Mokopi Jatinangor',
                'deskripsi' => 'Mokopi Jatinangor menjadi salah satu destinasi favorit untuk nongkrong santai bersama teman. Tempat ini mengusung konsep semi outdoor dengan area yang cukup luas serta tersedia lantai dua untuk pengunjung.',
                'alamat_lengkap' => 'Blk. T No.8, Cibeusi, Kec. Jatinangor, Kabupaten Sumedang, Jawa Barat 45363',
                'latitude' => -6.937308190312654,
                'longitude' => 107.76502663330619,
                'harga_min' => 25000,
                'harga_max' => 50000,
                'status_aktif' => true,
                'tempat_unggulan' => false,
                'created_by' => 1,
            ],
            [
                'kategori_id' => 6,
                'mood_id' => 1,
                'nama_tempat' => 'Perkebunan Teh Rancabali',
                'deskripsi' => 'Kebun Teh Rancabali adalah destinasi agro wisata yang terkenal dengan keindahan panoramananya. Perkebunan teh milik Pabrik Teh Walini ini terletak di daerah perbatasan Bandung dengan Kabupaten Cianjur.',
                'alamat_lengkap' => 'R9XJ+P9Q, Patengan, Rancabali, Bandung Regency, West Java 40973',
                'latitude' => -7.150404685001057,
                'longitude' => 107.38100203035117,
                'harga_min' => 5000,
                'harga_max' => 10000,
                'status_aktif' => true,
                'tempat_unggulan' => true,
                'created_by' => 1,
            ],
            [
                'kategori_id' => 6,
                'mood_id' => 5,
                'nama_tempat' => 'Cikahuripan Green Canyon Saguling',
                'deskripsi' => 'Wisata ini sangat cocok bagi Kalangan yang senang Berjalan kaki. Anda bisa Bersantai dengan Menyusuri rute secara Perlahan, Menyeberangi sungai, hingga Akhirnya sampai di Tebing-Tebing Menjulang tinggi yang Tertutup air Berwarna Kehijauan.',
                'alamat_lengkap' => '39W6+HHW, Cianjur Saguling, Saguling, Kec. Batujajar, Kabupaten Bandung Barat, Jawa Barat 40561',
                'latitude' => -6.904174925507209,
                'longitude' => 107.35887742050544,
                'harga_min' => 10000,
                'harga_max' => 25000,
                'status_aktif' => true,
                'tempat_unggulan' => false,
                'created_by' => 1,
            ],
            [
                'kategori_id' => 6,
                'mood_id' => 5,
                'nama_tempat' => 'Stone Garden Citatah',
                'deskripsi' => 'Stone Garden Citatah merupakan situs warisan alam geopark berupa bebatuan karang atau gamping yang tersebar di atas perbukitan.',
                'alamat_lengkap' => 'Gunung Masigit, Citatah, Kec. Cipatat, Kabupaten Bandung Barat, Jawa Barat 40554',
                'latitude' => -6.8243519961394075,
                'longitude' => 107.43863530832218,
                'harga_min' => 12000,
                'harga_max' => 27000,
                'status_aktif' => true,
                'tempat_unggulan' => false,
                'created_by' => 1,
            ],
            [
                'kategori_id' => 6,
                'mood_id' => 3,
                'nama_tempat' => 'The Lodge Maribaya',
                'deskripsi' => 'Tempat yang gaboleh dilewatin kalau lagi liburan ke Lembang.',
                'alamat_lengkap' => 'The Lodge Maribaya Lembang adalah destinasi wisata alam moden yang menggabungkan rekreasi, fotografi, edukasi, dan konservasi. Dengan spot foto unik, wahana menarik, dan penginapan glamping yang nyaman, ia menjadi pilihan tepat untuk liburan keluarga, pasangan, atau rombongan.',
                'latitude' => -6.829205955181555,
                'longitude' => 107.6886402543513,
                'harga_min' => 65000,
                'harga_max' => 390000,
                'status_aktif' => true,
                'tempat_unggulan' => false,
                'created_by' => 1,
            ],
            [
                'kategori_id' => 6,
                'mood_id' => 5,
                'nama_tempat' => 'Sanghyang Heuleut',
                'deskripsi' => 'Tanghyang Heuleut merupakan destinasi wisata telaga alami yang ada di Bandung Barat. Tempat wisata ini dikelilingi oleh tanaman hijau, udara segar, dan pemandangan yang indah. Suasana yang menenangkan membantu mengurangi tingkat stres dan meningkatkan rasa tenang yang sering kali hilang di tengah kebisingan kehidupan kota.',
                'alamat_lengkap' => ' Kp, Cipanas, Rajamandala Kulon, Kec. Cipatat, Kabupaten Bandung Barat, Jawa Barat 40554',
                'latitude' => -6.876321363239089,
                'longitude' => 107.34328045065106,
                'harga_min' => 10000,
                'harga_max' => 100000,
                'status_aktif' => true,
                'tempat_unggulan' => false,
                'created_by' => 1,
            ],
            [
                'kategori_id' => 6,
                'mood_id' => 1,
                'nama_tempat' => 'Selasar Sunaryo Art Space',
                'deskripsi' => 'Selasar Sunaryo Art Space (SSAS) merupakan hidden gem Bandung yang wajib dikunjungi bagi kamu penikmat seni dan literasi. Tempat ini merupakan galeri seni dan organisasi non-profit yang bertujuan mendukung perkembangan seni dan kebudayaan di Indonesia.',
                'alamat_lengkap' => 'Jl. Bukit Pakar Timur No.100, Ciburial, Kec. Cimenyan, Kabupaten Bandung, Jawa Barat 40198',
                'latitude' => -6.858313547756057,
                'longitude' => 107.63706041071319,
                'harga_min' => 35000,
                'harga_max' => 45000,
                'status_aktif' => true,
                'tempat_unggulan' => true,
                'created_by' => 1,
            ],
            [
                'kategori_id' => 2,
                'mood_id' => 3,
                'nama_tempat' => 'Kampung Daun',
                'deskripsi' => 'Kampung Daun Culture Gallery & Cafe menjadi destinasi wisata yang unik karena menawarkan kombinasi antara galeri seni, restoran, dan suasana pedesaan. Wisata bernuansa alam ini hanya berjarak 15 kilometer dari Alun-alun Kota Bandung sehingga tidak begitu sulit untuk dihampiri.',
                'alamat_lengkap' => 'Jl. Villa Triniti, Cigugur Girang, Kec. Parongpong, Kabupaten Bandung Barat, Jawa Barat 40559',
                'latitude' => -6.816819868490569,
                'longitude' => 107.58987612605578,
                'harga_min' => 75000,
                'harga_max' => 200000,
                'status_aktif' => true,
                'tempat_unggulan' => true,
                'created_by' => 1,
            ],
            [
                'kategori_id' => 6,
                'mood_id' => 5,
                'nama_tempat' => 'The Great Asia Afrika',
                'deskripsi' => 'Hidden gem Bandung yang cukup unik dengan tema perkampungan Jepang ala Kyoto bisa kamu jumpai di Great Asia Afrika. Bahkan, pengunjung dapat menjumpai beberapa icon terkenal yang ada di Jepang, salah satunya gerbang merah atau yang dikenal dengan Gerbang Torii.',
                'alamat_lengkap' => 'Jl. Raya Lembang - Bandung No.71, Gudangkahuripan, Kec. Lembang, Kabupaten Bandung Barat, Jawa Barat 40391',
                'latitude' => -6.832370517420322,
                'longitude' => 107.60572836787978,
                'harga_min' => 50000,
                'harga_max' => 290000,
                'status_aktif' => true,
                'tempat_unggulan' => true,
                'created_by' => 1,
            ],
            [
                'kategori_id' => 6,
                'mood_id' => 5,
                'nama_tempat' => 'Curug Tilu Leuwi Opat',
                'deskripsi' => 'Curug Tilu Leuwi Opat, yang berada di Kabupaten Bandung Barat, sekitar satu jam dari pusat Kota Bandung, relatif mudah dijangkau wisatawan. Sudah begitu, di sini terdapat tiga curug sekaligus.',
                'alamat_lengkap' => 'Jl. Ciwangun Indah Camp, Cihanjuang Rahayu, Kec. Parongpong, Kabupaten Bandung Barat, Jawa Barat 40559',
                'latitude' => -6.832370517420322,
                'longitude' => 107.60572836787978,
                'harga_min' => 20000,
                'harga_max' => 35000,
                'status_aktif' => true,
                'tempat_unggulan' => true,
                'created_by' => 1,
            ],
            [
                'kategori_id' => 1,
                'mood_id' => 1,
                'nama_tempat' => 'Kopi Mandja Dago',
                'deskripsi' => 'Coffee shop hits di Bandung yang bernama Kopi Mandja Coblong ini memiliki daya tarik yang tidak bisa diabaikan, terutama bagi kamu yang suka eksplorasi tempat nongkrong hits di Bandung.',
                'alamat_lengkap' => 'Jl. Ir. H. Juanda No.472, Dago, Kecamatan Coblong, Kota Bandung, Jawa Barat 40135',
                'latitude' => -6.866282511083737,
                'longitude' => 107.62156387817664,
                'harga_min' => 25000,
                'harga_max' => 50000,
                'status_aktif' => true,
                'tempat_unggulan' => false,
                'created_by' => 1,
            ],
            [
                'kategori_id' => 6,
                'mood_id' => 3,
                'nama_tempat' => 'Farmhouse Susu Lembang',
                'deskripsi' => 'Farmhouse Lembang adalah salah satu tempat rekreasi terkenal di Lembang yang menawarkan berbagai aktivitas mulai dari berinteraksi dengan hewan lebih dekat dan spot-spot foto keren.',
                'alamat_lengkap' => 'Jl. Raya Lembang No.108, Gudangkahuripan, Kec. Lembang, Kabupaten Bandung Barat, Jawa Barat 40391',
                'latitude' => -6.832851485283814,
                'longitude' => 107.60582427254126,
                'harga_min' => 30000,
                'harga_max' => 50000,
                'status_aktif' => true,
                'tempat_unggulan' => true,
                'created_by' => 1,
            ],
            [
                'kategori_id' => 6,
                'mood_id' => 3,
                'nama_tempat' => 'Floating Market Lembang',
                'deskripsi' => 'Floating Market Lembang adalah tempat wisata di daerah Lembang yang terkenal dengan konsep pasar terapung di atas danau. Pengunjung bisa membeli berbagai makanan dan minuman dari perahu-perahu yang berada di pinggir danau. Selain kuliner, tempat ini juga memiliki banyak wahana dan spot foto menarik, sehingga cocok untuk liburan bersama keluarga maupun teman.',
                'alamat_lengkap' => 'Jalan Grand Hotel No. 33E, Lembang, Kabupaten Bandung Barat.',
                'latitude' => -6.817637368218187,
                'longitude' => 107.61884073095986,
                'harga_min' => 30000,
                'harga_max' => 200000,
                'status_aktif' => true,
                'tempat_unggulan' => false,
                'created_by' => 1,
            ],
            [
                'kategori_id' => 6,
                'mood_id' => 3,
                'nama_tempat' => 'Lembang Park & Zoo',
                'deskripsi' => 'Lembang Park and Zoo mengombinasikan taman wisata yang luas dengan kebun binatang. Jadi pengunjung tidak hanya bisa bertemu dengan binatang saja, tetapi beraktivitas santai dengan berbagai fasilitas yang tersedia di Lembang Park and Zoo, dari naik kano di danau buatan, naik kuda, hingga berkeliling area Lembang Park and Zoo yang luas dengan scooter.',
                'alamat_lengkap' => 'Jalan Grand Hotel No. 33E, Lembang, Kabupaten Bandung Barat.',
                'latitude' => -6.804042140834796,
                'longitude' => 107.59203990832205,
                'harga_min' => 50000,
                'harga_max' => 100000,
                'status_aktif' => true,
                'tempat_unggulan' => true,
                'created_by' => 1,
            ],
            [
                'kategori_id' => 6,
                'mood_id' => 5,
                'nama_tempat' => 'Taman Hutan Raya Ir. H. Djuanda',
                'deskripsi' => 'Taman Hutan Raya Ir. H. Djuanda atau yang biasa disebut Tahura merupakan kawasan wisata alam di Bandung yang memiliki hutan hijau, udara sejuk, serta berbagai tempat bersejarah. Di dalamnya terdapat objek wisata seperti Goa Jepang, Goa Belanda, dan beberapa air terjun yang menarik untuk dikunjungi. Tahura cocok dijadikan tempat rekreasi, olahraga, maupun edukasi tentang alam dan sejarah.',
                'alamat_lengkap' => 'Jl. Pakar Bar. Jl. Ir. H. Juanda No.99, Ciburial, Kec. Cimenyan, Kabupaten Bandung, Jawa Barat 40198',
                'latitude' => -6.854301269112371,
                'longitude' => 107.63015768038684,
                'harga_min' => 17000,
                'harga_max' => 100000,
                'status_aktif' => true,
                'tempat_unggulan' => true,
                'created_by' => 1,
            ],
            [
                'kategori_id' => 6,
                'mood_id' => 5,
                'nama_tempat' => 'Kawah Putih',
                'deskripsi' => 'Kawah Putih merupakan destinasi wisata alam berupa kawah vulkanik yang terletak di kaki Gunung Patuha. Tempat ini terkenal dengan danau kawahnya yang berwarna putih kehijauan, serta suasana sejuk dan berkabut yang menambah keindahan alamnya.',
                'alamat_lengkap' => 'Sugihmukti, Pasirjambu, Bandung Regency, West Java',
                'latitude' => -7.166047574078268,
                'longitude' => 107.40241857241045,
                'harga_min' => 18000,
                'harga_max' => 200000,
                'status_aktif' => true,
                'tempat_unggulan' => true,
                'created_by' => 1,
            ],
            [
                'kategori_id' => 5,
                'mood_id' => 3,
                'nama_tempat' => 'Trans Studio Bandung',
                'deskripsi' => 'Trans Studio Bandung merupakan taman hiburan indoor terbesar di Bandung yang menawarkan berbagai wahana seru dan atraksi menarik. Tempat wisata ini memiliki beragam permainan, mulai dari wahana ekstrem hingga area hiburan keluarga dan anak-anak. Selain bermain, pengunjung juga dapat menikmati pertunjukan, berfoto di spot menarik, serta mencoba berbagai kuliner di dalam area wisata. Tempat ini cocok untuk rekreasi bersama keluarga maupun teman.',
                'alamat_lengkap' => 'Trans Studio Mall, Kecamatan Batununggal, Jl. Gatot Subroto No.289A, Cibangkong, Kota Bandung, Jawa Barat 40273',
                'latitude' => -6.925413786385778,
                'longitude' => 107.6362785941384,
                'harga_min' => 200000,
                'harga_max' => 500000,
                'status_aktif' => true,
                'tempat_unggulan' => false,
                'created_by' => 1,
            ],
            [
                'kategori_id' => 5,
                'mood_id' => 1,
                'nama_tempat' => 'Gedung Sate',
                'deskripsi' => 'Gedung Sate telah menjadi salah satu tujuan objek wisata di kota Bandung. Khusus wisatawan manca negara banyak dari mereka yang sengaja berkunjung karena memiliki keterkaitan emosi maupun history pada Gedung ini.',
                'alamat_lengkap' => 'Jl. Diponegoro No.22, Citarum, Kec. Bandung Wetan, Kota Bandung, Jawa Barat 40115',
                'latitude' => -6.9022298549959595,
                'longitude' => 107.61918477659678,
                'harga_min' => 5000,
                'harga_max' => 15000,
                'status_aktif' => true,
                'tempat_unggulan' => false,
                'created_by' => 1,
            ]
        ];

        foreach ($places as $place) {
            $moodId = $place['mood_id'];
            unset($place['mood_id']);

            $placeId = DB::table('places')->insertGetId(array_merge($place, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));

            // insert ke tabel pivot
            DB::table('place_moods')->insert([
                'place_id' => $placeId,
                'mood_id'  => $moodId,
            ]);
        }
    }
}
